import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { AuthTemplate } from "@/components/template/auth/auth-tpt";
import Loader from "@/components/template/loader/Loader";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const token = true


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} w-screen h-screen `}>
        <Loader />
        <div className="max-w-[30rem] max-h-full h-full p-5 flex flex-col mx-auto gap-5">
          <AuthTemplate>
            {children}
          </AuthTemplate>
        </div>
      </body>
    </html>
  );
}
