import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { AuthTemplate } from "@/components/template/auth/auth-tpt";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('test server')
  const token = (await cookies()).get('x-token-api')?.value || null;
  console.log(token)
  const data = await fetch('http://localhost:3000/api', {
    method: 'POST',
    headers: {
      'x-token-api': 'AIzaSyDZ4t4xLaN0uhdB6VCwQvwLsubkZdHIESM'
    }
  })

  console.log('data', data)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  bg-red-500 antialiased`}
      >
        <AuthTemplate token={token}>
          {children}
        </AuthTemplate>
      </body>
    </html>
  );
}
